### ISSUE TITLE
Output data in correct format and submit to forcast hub.

### ISSUE THREAD

**Issue by michaelmunie** [qjhong/qjhong.github.io#2]
It would help your model get more views if you output the data in the following format and submit to the github project below, which serves as a central location for many forecasts, as well as a well of comparing model performance in a standard way and also powering a larger ensemble model.

[https://github.com/reichlab/covid19-forecast-hub#forecast-file-format](https://github.com/reichlab/covid19-forecast-hub#forecast-file-format)

**Comment by qjhong** [comment]
Thank you for letting me know! I just submitted a request to forcast hub. Again, appreciate your suggestion.
